### ISSUE TITLE
Usage in ListView/GridView

### ISSUE THREAD

**Issue by svenporto** [chrisbanes/Android-BitmapCache#1]
Is there a sample app using `ListView/GridView`?

The problem is that I adapted your sample for `ViewPager` but I keep getting errors because bitmaps that are in cache are being recycled too early and therefore I keep getting errors - possible because of reusing and `ViewHolder pattern` in `ListView`?

If I start the app  first time - everything is working, I close the activity and app (back button), re-open and none of the images is displayed (tries to use all those already recycled views).

Till then I'll probably stick with [Android Guide on Bitmaps caching](http://developer.android.com/training/displaying-bitmaps/cache-bitmap.html) but would like to know the solution.

Thanks.

**Comment by chrisbanes** [comment]
This should be fixed now.
