### ISSUE TITLE
Usage with bitmaps that are not fetched from a Url (example a Resource Drawable)?

### ISSUE THREAD

**Issue by curioustechizen** [chrisbanes/Android-BitmapCache#4]
The library uses an image Url as the source of a bitmap (and to identify a bitmap uniquely). Can this be used with "local" bitmaps (i.e., those decoded from file/resources)?

**Comment by chrisbanes** [comment]
Yes, you'll just need to generate a unique URL yourself. It doesn't need to be any specific format, just unique to the image.

For File's I would do this:

``` java
File file = new File("/path/to/file");
String url = Uri.fromFile(file).toString();
```

For resources you could do this:

``` java
String url = "app://resources/" + R.drawable.blah;
```
